
package json23plet.ontologies;

import java.nio.file.Path;
import java.nio.file.Paths;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

public class JbsOntology
    extends BaseOntology
{
    private static Paths paths;
    public static Path ontPath = (Paths.get("ontologies", "ttl", "JbsOntology" + ".ttl"));
    public static ModelFactory smodel;
    public static OntModel model = ((OntModel) ((OntModel) ModelFactory.createOntologyModel()).read(ontPath.toString()));
    public static String JBO_PREFIX = "jbo";
    public static String JBR_PREFIX = "jbr";
    public static String JBO_URI = "http://jbs.technion.ac.il/ontology/";
    public static String JBR_URI = "http://jbs.technion.ac.il/resource/";
    public static Resource JBO_C_TANACH = (model.getOntClass(JBO_URI + "Tanach"));
    public static Resource JBO_C_MISHNA = (model.getOntClass(JBO_URI + "Mishna"));
    public static Resource JBO_C_TALMUDBAVLI = (model.getOntClass(JBO_URI + "TalmudBavli"));
    public static Resource JBO_C_MISHNETORAH = (model.getOntClass(JBO_URI + "MishneTorah"));
    public static Resource JBO_C_SHULCHANARUCH = (model.getOntClass(JBO_URI + "ShulchanAruch"));
    public static Resource JBO_C_SIFREYRAVKUK = (model.getOntClass(JBO_URI + "SifreyRavKuk"));
    public static Resource JBO_C_SIFREYRAMCHAL = (model.getOntClass(JBO_URI + "SifreyRamchal"));
    public static Resource JBO_C_PASUK = (model.getOntClass(JBO_URI + "Pasuk"));
    public static Resource JBO_C_PERUSHTANACH = (model.getOntClass(JBO_URI + "PerushTanach"));
    public static Resource JBO_C_PASUKTORAH = (model.getOntClass(JBO_URI + "PasukTorah"));
    public static Resource JBO_C_PASUKNEVIYIM = (model.getOntClass(JBO_URI + "PasukNeviyim"));
    public static Resource JBO_C_PASUKKETUVIM = (model.getOntClass(JBO_URI + "PasukKetuvim"));
    public static Resource JBO_C_PASUKBERESHIT = (model.getOntClass(JBO_URI + "PasukBereshit"));
    public static Resource JBO_C_PASUKSHEMOT = (model.getOntClass(JBO_URI + "PasukShemot"));
    public static Resource JBO_C_PASUKVAYIKRA = (model.getOntClass(JBO_URI + "PasukVayikra"));
    public static Resource JBO_C_PASUKBAMIDBAR = (model.getOntClass(JBO_URI + "PasukBamidbar"));
    public static Resource JBO_C_PASUKDEVARIM = (model.getOntClass(JBO_URI + "PasukDevarim"));
    public static Resource JBO_C_PASUKYEHOSHUA = (model.getOntClass(JBO_URI + "PasukYehoshua"));
    public static Resource JBO_C_PASUKSHOFTIM = (model.getOntClass(JBO_URI + "PasukShoftim"));
    public static Resource JBO_C_PASUKSHEMUELA = (model.getOntClass(JBO_URI + "PasukShemuelA"));
    public static Resource JBO_C_PASUKSHEMUELB = (model.getOntClass(JBO_URI + "PasukShemuelB"));
    public static Resource JBO_C_PASUKMELACHIMA = (model.getOntClass(JBO_URI + "PasukMelachimA"));
    public static Resource JBO_C_PASUKMELACHIMB = (model.getOntClass(JBO_URI + "PasukMelachimB"));
    public static Resource JBO_C_PASUKYESHAAYA = (model.getOntClass(JBO_URI + "PasukYeshaaya"));
    public static Resource JBO_C_PASUKYIRMIYA = (model.getOntClass(JBO_URI + "PasukYirmiya"));
    public static Resource JBO_C_PASUKYECHEZKEL = (model.getOntClass(JBO_URI + "PasukYechezkel"));
    public static Resource JBO_C_PASUKHOSHEA = (model.getOntClass(JBO_URI + "PasukHoshea"));
    public static Resource JBO_C_PASUKYOEL = (model.getOntClass(JBO_URI + "PasukYoel"));
    public static Resource JBO_C_PASUKAMOS = (model.getOntClass(JBO_URI + "PasukAmos"));
    public static Resource JBO_C_PASUKOVADYA = (model.getOntClass(JBO_URI + "PasukOvadya"));
    public static Resource JBO_C_PASUKYONA = (model.getOntClass(JBO_URI + "PasukYona"));
    public static Resource JBO_C_PASUKMICHA = (model.getOntClass(JBO_URI + "PasukMicha"));
    public static Resource JBO_C_PASUKNACHUM = (model.getOntClass(JBO_URI + "PasukNachum"));
    public static Resource JBO_C_PASUKCHAVAKUK = (model.getOntClass(JBO_URI + "PasukChavakuk"));
    public static Resource JBO_C_PASUKTZEFANYA = (model.getOntClass(JBO_URI + "PasukTzefanya"));
    public static Resource JBO_C_PASUKCHAGAY = (model.getOntClass(JBO_URI + "PasukChagay"));
    public static Resource JBO_C_PASUKZECHARYA = (model.getOntClass(JBO_URI + "PasukZecharya"));
    public static Resource JBO_C_PASUKMALACHI = (model.getOntClass(JBO_URI + "PasukMalachi"));
    public static Resource JBO_C_PASUKTEHILIM = (model.getOntClass(JBO_URI + "PasukTehilim"));
    public static Resource JBO_C_PASUKMISHLEY = (model.getOntClass(JBO_URI + "PasukMishley"));
    public static Resource JBO_C_PASUKIYOV = (model.getOntClass(JBO_URI + "PasukIyov"));
    public static Resource JBO_C_PASUKSHIRHASHIRIM = (model.getOntClass(JBO_URI + "PasukShirHashirim"));
    public static Resource JBO_C_PASUKRUT = (model.getOntClass(JBO_URI + "PasukRut"));
    public static Resource JBO_C_PASUKEYCHA = (model.getOntClass(JBO_URI + "PasukEycha"));
    public static Resource JBO_C_PASUKKOHELET = (model.getOntClass(JBO_URI + "PasukKohelet"));
    public static Resource JBO_C_PASUKESTER = (model.getOntClass(JBO_URI + "PasukEster"));
    public static Resource JBO_C_PASUKDANIEL = (model.getOntClass(JBO_URI + "PasukDaniel"));
    public static Resource JBO_C_PASUKEZRA = (model.getOntClass(JBO_URI + "PasukEzra"));
    public static Resource JBO_C_PASUKNECHEMYA = (model.getOntClass(JBO_URI + "PasukNechemya"));
    public static Resource JBO_C_PASUKDIVREYHAYAMIMA = (model.getOntClass(JBO_URI + "PasukDivreyHayamimA"));
    public static Resource JBO_C_PASUKDIVREYHAYAMIMB = (model.getOntClass(JBO_URI + "PasukDivreyHayamimB"));
    public static Resource JBO_C_PERUSHRASHI = (model.getOntClass(JBO_URI + "PerushRashi"));
    public static Resource JBO_C_PERUSHSIFTEYCHACHAMIN = (model.getOntClass(JBO_URI + "PerushSifteyChachamin"));
    public static Resource JBO_C_PERUSHRAMBAN = (model.getOntClass(JBO_URI + "PerushRamban"));
    public static Resource JBO_C_TARGUMYONATAN = (model.getOntClass(JBO_URI + "TargumYonatan"));
    public static Resource JBO_C_PERUSHORHACHAYIM = (model.getOntClass(JBO_URI + "PerushOrHachayim"));
    public static Resource JBO_C_PERUSHRABIAVRAHAMIBNEZRA = (model.getOntClass(JBO_URI + "PerushRabiAvrahamIbnEzra"));
    public static Resource JBO_C_PERUSHBAALHATURIM = (model.getOntClass(JBO_URI + "PerushBaalHaturim"));
    public static Resource JBO_C_TARGUMONKELOS = (model.getOntClass(JBO_URI + "TargumOnkelos"));
    public static Resource JBO_C_PERUSHSEFORNO = (model.getOntClass(JBO_URI + "PerushSeforno"));
    public static Resource JBO_C_PERUSHKELIYEKAR = (model.getOntClass(JBO_URI + "PerushKeliYekar"));
    public static Resource JBO_C_PERUSHDAATZEKENIM = (model.getOntClass(JBO_URI + "PerushDaatZekenim"));
    public static Resource JBO_C_MIDRASHRABA = (model.getOntClass(JBO_URI + "MidrashRaba"));
    public static Resource JBO_C_MIDRASHTANCHUMA = (model.getOntClass(JBO_URI + "MidrashTanchuma"));
    public static Resource JBO_C_PERUSHMETZUDATDAVID = (model.getOntClass(JBO_URI + "PerushMetzudatDavid"));
    public static Resource JBO_C_PERUSHMETZUDATTZIYON = (model.getOntClass(JBO_URI + "PerushMetzudatTziyon"));
    public static Resource JBO_C_PERUSHRALBAG = (model.getOntClass(JBO_URI + "PerushRalbag"));
    public static Resource JBO_C_PERUSHMALBIM = (model.getOntClass(JBO_URI + "PerushMalbim"));
    public static Resource JBO_C_PERUSHMALBIMBEURHAINYAN = (model.getOntClass(JBO_URI + "PerushMalbimBeurHainyan"));
    public static Resource JBO_C_PERUSHMALBIMBEURHAMILOT = (model.getOntClass(JBO_URI + "PerushMalbimBeurHamilot"));
    public static Resource JBO_C_SEFERHAMITZVOT = (model.getOntClass(JBO_URI + "SeferHamitzvot"));
    public static Resource JBO_C_SHEMONAKEVATZIM = (model.getOntClass(JBO_URI + "ShemonaKevatzim"));
    public static Resource JBO_C_OROT = (model.getOntClass(JBO_URI + "Orot"));
    public static Resource JBO_C_MESILATYESHARIM = (model.getOntClass(JBO_URI + "MesilatYesharim"));
    public static Property JBO_P_MENTIONS = (model.getOntProperty(JBO_URI + "mentions"));
    public static Property JBO_P_INTERPRETS = (model.getOntProperty(JBO_URI + "interprets"));
    public static Property JBO_P_CONTENT = (model.getOntProperty(JBO_URI + "content"));
    public static Property JBO_P_CONTAINER = (model.getOntProperty(JBO_URI + "container"));
    public static Property JBO_P_POSITION = (model.getOntProperty(JBO_URI + "position"));
    public static Property JBO_P_TEXT = (model.getOntProperty(JBO_URI + "text"));
    public static Property JBO_P_TEXTNIKUD = (model.getOntProperty(JBO_URI + "textNikud"));
    public static Property JBO_P_POSITIONINPEREK = (model.getOntProperty(JBO_URI + "positionInPerek"));
    public static Property JBO_P_POSITIONINPARASHA = (model.getOntProperty(JBO_URI + "positionInParasha"));
}
