
package json23plet.ontologies;

import org.apache.jena.ontology.OntModel;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

public class JbsOntology
    extends BaseOntology
{
    public static ModelFactory smodel;
    public static OntModel model = ((OntModel) ((OntModel) ModelFactory.createOntologyModel()).read("ontologies\ttl\JbsOntology.ttl"));
    public static String JBO_PREFIX = "jbo";
    public static String JBR_PREFIX = "jbr";
    public static String JBO_URI = "http://jbs.technion.ac.il/ontology/";
    public static String JBR_URI = "http://jbs.technion.ac.il/resource/";
    public static Resource JBO_C_TANACH = (model.getOntClass(JBO_URI + "Tanach"));
    public static Resource JBO_C_MISHNA = (model.getOntClass(JBO_URI + "Mishna"));
    public static Resource JBO_C_TALMUDBAVLI = (model.getOntClass(JBO_URI + "TalmudBavli"));
    public static Resource JBO_C_MISHNETORAH = (model.getOntClass(JBO_URI + "MishneTorah"));
    public static Resource JBO_C_SHULCHANARUCH = (model.getOntClass(JBO_URI + "ShulchanAruch"));
    public static Resource JBO_C_SIFREYRAVKUK = (model.getOntClass(JBO_URI + "SifreyRavKuk"));
    public static Resource JBO_C_SIFREYRAMCHAL = (model.getOntClass(JBO_URI + "SifreyRamchal"));
    public static Resource JBO_C_TORAH = (model.getOntClass(JBO_URI + "Torah"));
    public static Resource JBO_C_NEVIYIM = (model.getOntClass(JBO_URI + "Neviyim"));
    public static Resource JBO_C_KETUVIM = (model.getOntClass(JBO_URI + "Ketuvim"));
    public static Resource JBO_C_PERUSHTANACH = (model.getOntClass(JBO_URI + "PerushTanach"));
    public static Resource JBO_C_BERESHIT = (model.getOntClass(JBO_URI + "Bereshit"));
    public static Resource JBO_C_SHEMOT = (model.getOntClass(JBO_URI + "Shemot"));
    public static Resource JBO_C_VAYIKRA = (model.getOntClass(JBO_URI + "Vayikra"));
    public static Resource JBO_C_BAMIDBAR = (model.getOntClass(JBO_URI + "Bamidbar"));
    public static Resource JBO_C_DEVARIM = (model.getOntClass(JBO_URI + "Devarim"));
    public static Resource JBO_C_YEHOSHUA = (model.getOntClass(JBO_URI + "Yehoshua"));
    public static Resource JBO_C_SHOFTIM = (model.getOntClass(JBO_URI + "Shoftim"));
    public static Resource JBO_C_SHEMUELA = (model.getOntClass(JBO_URI + "ShemuelA"));
    public static Resource JBO_C_SHEMUELB = (model.getOntClass(JBO_URI + "ShemuelB"));
    public static Resource JBO_C_MELACHIMA = (model.getOntClass(JBO_URI + "MelachimA"));
    public static Resource JBO_C_MELACHIMB = (model.getOntClass(JBO_URI + "MelachimB"));
    public static Resource JBO_C_YESHAAYA = (model.getOntClass(JBO_URI + "Yeshaaya"));
    public static Resource JBO_C_YIRMIYA = (model.getOntClass(JBO_URI + "Yirmiya"));
    public static Resource JBO_C_YECHEZKEL = (model.getOntClass(JBO_URI + "Yechezkel"));
    public static Resource JBO_C_HOSHEA = (model.getOntClass(JBO_URI + "Hoshea"));
    public static Resource JBO_C_YOEL = (model.getOntClass(JBO_URI + "Yoel"));
    public static Resource JBO_C_AMOS = (model.getOntClass(JBO_URI + "Amos"));
    public static Resource JBO_C_OVADYA = (model.getOntClass(JBO_URI + "Ovadya"));
    public static Resource JBO_C_YONA = (model.getOntClass(JBO_URI + "Yona"));
    public static Resource JBO_C_MICHA = (model.getOntClass(JBO_URI + "Micha"));
    public static Resource JBO_C_NACHUM = (model.getOntClass(JBO_URI + "Nachum"));
    public static Resource JBO_C_CHAVAKUK = (model.getOntClass(JBO_URI + "Chavakuk"));
    public static Resource JBO_C_TZEFANYA = (model.getOntClass(JBO_URI + "Tzefanya"));
    public static Resource JBO_C_CHAGAY = (model.getOntClass(JBO_URI + "Chagay"));
    public static Resource JBO_C_ZECHARYA = (model.getOntClass(JBO_URI + "Zecharya"));
    public static Resource JBO_C_MALACHI = (model.getOntClass(JBO_URI + "Malachi"));
    public static Resource JBO_C_TEHILIM = (model.getOntClass(JBO_URI + "Tehilim"));
    public static Resource JBO_C_MISHLEY = (model.getOntClass(JBO_URI + "Mishley"));
    public static Resource JBO_C_IYOV = (model.getOntClass(JBO_URI + "Iyov"));
    public static Resource JBO_C_SHIRHASHIRIM = (model.getOntClass(JBO_URI + "ShirHashirim"));
    public static Resource JBO_C_RUT = (model.getOntClass(JBO_URI + "Rut"));
    public static Resource JBO_C_EYCHA = (model.getOntClass(JBO_URI + "Eycha"));
    public static Resource JBO_C_KOHELET = (model.getOntClass(JBO_URI + "Kohelet"));
    public static Resource JBO_C_ESTER = (model.getOntClass(JBO_URI + "Ester"));
    public static Resource JBO_C_DANIEL = (model.getOntClass(JBO_URI + "Daniel"));
    public static Resource JBO_C_EZRA = (model.getOntClass(JBO_URI + "Ezra"));
    public static Resource JBO_C_NECHEMYA = (model.getOntClass(JBO_URI + "Nechemya"));
    public static Resource JBO_C_DIVREYHAYAMIMA = (model.getOntClass(JBO_URI + "DivreyHayamimA"));
    public static Resource JBO_C_DIVREYHAYAMIMB = (model.getOntClass(JBO_URI + "DivreyHayamimB"));
    public static Resource JBO_C_RASHI = (model.getOntClass(JBO_URI + "Rashi"));
    public static Resource JBO_C_SIFTEYCHACHAMIN = (model.getOntClass(JBO_URI + "SifteyChachamin"));
    public static Resource JBO_C_RAMBAN = (model.getOntClass(JBO_URI + "Ramban"));
    public static Resource JBO_C_TARGUMYONATAN = (model.getOntClass(JBO_URI + "TargumYonatan"));
    public static Resource JBO_C_ORHACHAYIM = (model.getOntClass(JBO_URI + "OrHachayim"));
    public static Resource JBO_C_RABIAVRAHAMIBNEZRA = (model.getOntClass(JBO_URI + "RabiAvrahamIbnEzra"));
    public static Resource JBO_C_BAALHATURIM = (model.getOntClass(JBO_URI + "BaalHaturim"));
    public static Resource JBO_C_TARGUMONKELOS = (model.getOntClass(JBO_URI + "TargumOnkelos"));
    public static Resource JBO_C_SEFORNO = (model.getOntClass(JBO_URI + "Seforno"));
    public static Resource JBO_C_KELIYEKAR = (model.getOntClass(JBO_URI + "KeliYekar"));
    public static Resource JBO_C_DAATZEKENIM = (model.getOntClass(JBO_URI + "DaatZekenim"));
    public static Resource JBO_C_MIDRASHRABA = (model.getOntClass(JBO_URI + "MidrashRaba"));
    public static Resource JBO_C_MIDRASHTANCHUMA = (model.getOntClass(JBO_URI + "MidrashTanchuma"));
    public static Resource JBO_C_METZUDATDAVID = (model.getOntClass(JBO_URI + "MetzudatDavid"));
    public static Resource JBO_C_METZUDATTZIYON = (model.getOntClass(JBO_URI + "MetzudatTziyon"));
    public static Resource JBO_C_RALBAG = (model.getOntClass(JBO_URI + "Ralbag"));
    public static Resource JBO_C_MALBIM = (model.getOntClass(JBO_URI + "Malbim"));
    public static Resource JBO_C_MALBIMBEURHAINYAN = (model.getOntClass(JBO_URI + "MalbimBeurHainyan"));
    public static Resource JBO_C_MALBIMBEURHAMILOT = (model.getOntClass(JBO_URI + "MalbimBeurHamilot"));
    public static Resource JBO_C_SEFERHAMITZVOT = (model.getOntClass(JBO_URI + "SeferHamitzvot"));
    public static Resource JBO_C_SHEMONAKEVATZIM = (model.getOntClass(JBO_URI + "ShemonaKevatzim"));
    public static Resource JBO_C_OROT = (model.getOntClass(JBO_URI + "Orot"));
    public static Resource JBO_C_MESILATYESHARIM = (model.getOntClass(JBO_URI + "MesilatYesharim"));
    public static Property JBO_P_MENTIONS = (model.getOntProperty(JBO_URI + "mentions"));
    public static Property JBO_P_INTERPRETS = (model.getOntProperty(JBO_URI + "interprets"));
    public static Property JBO_P_CONTENT = (model.getOntProperty(JBO_URI + "content"));
    public static Property JBO_P_CONTAINER = (model.getOntProperty(JBO_URI + "container"));
    public static Property JBO_P_POSITION = (model.getOntProperty(JBO_URI + "position"));
    public static Property JBO_P_TEXT = (model.getOntProperty(JBO_URI + "text"));
    public static Property JBO_P_TEXTNIKUD = (model.getOntProperty(JBO_URI + "textNikud"));
    public static Property JBO_P_POSITIONINPEREK = (model.getOntProperty(JBO_URI + "positionInPerek"));
    public static Property JBO_P_POSITIONINPARASHA = (model.getOntProperty(JBO_URI + "positionInParasha"));
}
